[tool.poetry]
name = "libstreamvbyte"
version = "0.1.0"
description = ""
authors = ["Xyphuz <hansen0715.2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pybind11 = "^2.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
