name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Setup Python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.4"

      - name: Install pytest
        run: pip install pytest
        
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - name: Build
        run: |
          cmake . -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Test
        run: |
          ./test
          pytest ./tests/test.py
