name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Setup Python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.4"

      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Setup Python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.4"

      - uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_ARCHS_MACOS: universal2
          CIBW_ARCHS_LINUX: "auto aarch64"

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
